name: cargo_quest_tycoon
description: "Cargo quest tycoon game"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flame: ^1.21.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/map/
